name: Version Release

on:
  push:
    tags:
      - 'v*'  # Trigger this on tags starting with v (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create a release and upload assets

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive source files as .zip and .tar.gz
      run: |
        mkdir -p release
        zip -r release/simple-banking.zip . -x "release/*"
        tar -czf release/simple-banking.tar.gz . --exclude=release

    - name: Upload release assets to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/simple-banking.zip
          release/simple-banking.tar.gz
          build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
