name: Test Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0-test)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: ./gradlew build

      - name: Package source as zip and tar.gz
        run: |
          mkdir -p release
          zip -r release/source-${{ github.event.inputs.version }}.zip . -x release/\*
          tar -czf release/source-${{ github.event.inputs.version }}.tar.gz .

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Create Draft Pre-Release with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.version }} \
            release/source-${{ github.event.inputs.version }}.zip \
            release/source-${{ github.event.inputs.version }}.tar.gz \
            build/libs/*.jar \
            --title "Test Release ${{ github.event.inputs.version }}" \
            --notes "This is a test prerelease." \
            --draft \
            --prerelease
