name: Version Release

on:
  push:
    tags:
      - 'v*'  # Trigger this on tags starting with v (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest  # Run the release job on the latest Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # This checks out your repository's code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'  # Use Temurin (OpenJDK build)

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew build  # Builds the .jar file from your Java code

    - name: Archive source files as .zip
      run: |
        mkdir -p release  # Create a release directory
        zip -r release/simple-banking.zip .  # Create a .zip file of the source code
        tar -czf release/simple-banking.tar.gz .  # Create a .tar.gz file of the source code

    - name: Upload release assets to GitHub
      uses: softprops/action-gh-release@v1  # GitHub Action to upload assets to GitHub Releases
      with:
        files: |
            release/simple-banking.zip
            release/simple-banking.tar.gz  # Upload the files
            build/libs/*.jar  # Upload the .jar file generated by Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
