name: Version Release

on:
  push:
    tags:
      - 'v*'  # Trigger this on tags starting with v (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Create release directory
      run: mkdir -p release

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Archive source files
      run: |
        VERSION=${GITHUB_REF##*/}
        zip -r "release/simple-banking-${VERSION}.zip" . -x "release/*"
        tar -czf "release/simple-banking-${VERSION}.tar.gz" .

    - name: List release directory (debugging)
      run: ls -alh release

    - name: Upload release assets to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/simple-banking-${{ github.ref_name }}.zip
          release/simple-banking-${{ github.ref_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
