name: Version Release

on:
  push:
    tags:
      - 'v*'  # Trigger this on tags starting with v (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Create release directory
      run: mkdir -p release

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build with Gradle
      run: ./gradlew build

    - name: List files in build/libs
      run: ls -alh build/libs

    - name: Archive source files as .zip
      run: |
        VERSION=${GITHUB_REF##*/}
        echo "VERSION: ${VERSION}"  # For debugging
        mkdir -p release  # Ensure the release directory exists
        zip -r "release/simple-banking-${VERSION}.zip" . -x "release/*"
        tar -czf "release/simple-banking-${VERSION}.tar.gz" .

    - name: Upload release assets to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/simple-banking-${GITHUB_REF##*/}.zip
          release/simple-banking-${GITHUB_REF##*/}.tar.gz
          build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
