name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for GitHub CLI to create a release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Build project
        run: ./gradlew build

      - name: Create release directory
        run: mkdir -p release

      - name: Copy .jar to release directory
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
          cp "$JAR_FILE" release/

      - name: Archive source files
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          zip -r release/source-${VERSION}.zip .
          tar -czf release/source-${VERSION}.tar.gz .

      - name: Install GitHub CLI
        uses: cli/cli-action@v1

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create GitHub Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gh release create "$VERSION" \
            release/source-${VERSION}.zip \
            release/source-${VERSION}.tar.gz \
            release/*.jar \
            --title "$VERSION" \
            --notes "Automated release for $VERSION" \
            --prerelease
