name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a tag starting with "v" is pushed (e.g., v1.0.1)

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessary permission for creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Build the project
        run: ./gradlew build

      - name: Prepare release assets
        run: |
          mkdir -p release
          VERSION=${GITHUB_REF##*/}  # Extract tag name from ref
          zip -r release/source-${VERSION}.zip .
          tar -czf release/source-${VERSION}.tar.gz .
          mv build/libs/*.jar release/simple-banking-${VERSION}.jar

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create GitHub release with assets
        run: |
          VERSION=${GITHUB_REF##*/}
          gh release create "${VERSION}" \
            release/source-${VERSION}.zip \
            release/source-${VERSION}.tar.gz \
            release/simple-banking-${VERSION}.jar \
            --title "${VERSION}" \
            --notes "Automated release from tag push" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
