name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessary permission for creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: maven

      - name: Build the project
        run: ./gradlew build

      - name: Prepare release assets
        run: |
          mkdir -p release
          zip -r release/source-${{ github.event.inputs.version }}.zip .
          tar -czf release/source-${{ github.event.inputs.version }}.tar.gz .
          mv build/libs/*.jar release/simple-banking-${{ github.event.inputs.version }}.jar

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create GitHub release with assets
        run: |
          gh release create "v${{ github.event.inputs.version }}" \
            release/source-${{ github.event.inputs.version }}.zip \
            release/source-${{ github.event.inputs.version }}.tar.gz \
            release/simple-banking-${{ github.event.inputs.version }}.jar \
            --title "v${{ github.event.inputs.version }}" \
            --notes "Automated release from master" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Make sure the token is used correctly
