jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This grants write access to contents (releases included)
      actions: write   # Grant permission for actions to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the project
        run: ./gradlew build

      - name: Prepare release assets
        run: |
          mkdir -p release
          zip -r release/source-${{ github.event.inputs.version }}.zip .
          tar -czf release/source-${{ github.event.inputs.version }}.tar.gz .
          mv build/libs/*.jar release/simple-banking-${{ github.event.inputs.version }}.jar

      - name: Create GitHub release with assets
        run: |
          gh release create "v${{ github.event.inputs.version }}" \
            release/source-${{ github.event.inputs.version }}.zip \
            release/source-${{ github.event.inputs.version }}.tar.gz \
            release/simple-banking-${{ github.event.inputs.version }}.jar \
            --title "v${{ github.event.inputs.version }}" \
            --notes "Automated release from master" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is used correctly
